#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '👷🔨... Alright.... Building your project. 👷🔨'

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Build Successful... committing this now. ✅✅✅✅'
